### ISSUE TITLE
uninitialized class variable @@mtimes in Jekyll::StaticFile

### ISSUE THREAD

**Issue by ari** [stereobooster/jekyll-press#30]
Jekyll 3.2, Ruby 3.2.1.

```
bundler: failed to load command: jekyll (/Users/ari/.rbenv/versions/2.3.1/bin/jekyll)
NameError: uninitialized class variable @@mtimes in Jekyll::StaticFile
Did you mean?  mtimes
               @mtimes
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-press-0.2.1/lib/jekyll-press.rb:89:in `write'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:212:in `block in write'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:333:in `block (2 levels) in each_site_file'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `each'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:332:in `block in each_site_file'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:331:in `each_site_file'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:211:in `write'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/site.rb:71:in `process'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/command.rb:26:in `process_site'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/commands/build.rb:63:in `build'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/commands/build.rb:34:in `process'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/ari/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jekyll-3.2.0/exe/jekyll:13:in `<top (required)>'
  /Users/ari/.rbenv/versions/2.3.1/bin/jekyll:23:in `load'
  /Users/ari/.rbenv/versions/2.3.1/bin/jekyll:23:in `<top (required)>'
```

**Comment by gertoe** [comment]
I've issued a pull-request just right now that should fix that issue.

`@@mtimes` needs to be initialized as a class variable (see [this](https://www.codecademy.com/en/forum_questions/52b9ed0780ff331991003246)).

just append `@@mtimes = {}` after the `include Compressor` to initialize that array.

**Comment by michaelcurry** [comment]
Is there an update on this fix?  it is blocking me from building on the newest version on Jekyll

**Comment by gertoe** [comment]
Well, I do not have any issues with the workaround, though I have exchanged one component used by this plugin back in May, because I also had an issue with it. If you want, you may try my [fork](https://github.com/gertoe/jekyll-press.git) of jekyll-press in your _plugins directory.

What I have changed so far:
- @@mtimes-workaround
- removed version.rb ("previous definition of VERSION was here")
- CSS3-Syntax-Fix: using cssminify instead of multi_css

Latter may possibly fix your issue.

**Comment by michaelcurry** [comment]
Trying to stick to all gem installs and not have any package specific code in my repo 😢  

Was hoping @stereobooster would fix the issue or accept a PR.

On a side note: @gertoe thanks for the reply.  Looks like that workaround will work :+1:

**Comment by gordio** [comment]
I add `@@mtimes = {}`
after `require 'jekyll-press'` in file `_plugins/jekyll-press-plugin.rb` and "problem gone". :-)

**Comment by ParaplegicRacehorse** [comment]
Error still exists in jekyll-press gem.

**Comment by stereobooster** [comment]
project is deprecated https://github.com/stereobooster/jekyll-press/issues/35
